# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'QuizPlay iOS' do
 pod 'Mixpanel'
end

target 'QuizPlay Android' do

end

target 'QuizPlay Mac' do

end

